"use strict";

module.exports = {
  jobs: require("./jobs/state-machine"),
  auth: require("./auth"),
  passwordAuth: require("./auth/password-auth"),
  oauthBroker: require("./auth/oauth-broker"),
  uploadSessions: require("./uploads/sessions"),
  transferManager: require("./uploads/transfer-manager"),
  sandboxedWorkers: require("./workers/sandboxed"),
  sourceRetention: require("./retention/source"),
  credentialVault: require("./credentials/vault"),
  securityBoundaries: require("./security/boundaries"),
  durableStatus: require("./jobs/durable-status"),
  resultMetadata: require("./results/metadata"),
  resultHistory: require("./results/history"),
  submissionPipelineGate: require("./pipeline/submission-gate"),
  commercialGates: require("./commerce/commercial-gates"),
  providerCapacity: require("./commerce/provider-capacity"),
  customerOffer: require("./commerce/customer-offer"),
  paymentArchitecture: require("./commerce/payment-architecture"),
  providerOnboarding: require("./provider/onboarding"),
  legalTerms: require("./legal/terms"),
  legalPrivacy: require("./legal/privacy"),
  consentCopy: require("./legal/consent-copy"),
  entitlements: require("./commerce/entitlements"),
  checkout: require("./commerce/checkout"),
};
